name: regions_domain
description: Dart package which manages the business logic in the app
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  dio: ^5.5.0+1
  intl: ^0.19.0
  regions_data:
    path: ../regions_data

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
